# Generated by Django 4.2.2 on 2024-02-10 10:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_test_associated_module_delete_quiz_and_more'),
        ('quiz', '0002_quiz_course_quiz_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(null=True, blank=True,on_delete=django.db.models.deletion.CASCADE, related_name='quiz_course', to='main.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_module', to='main.module'),
            preserve_default=False,
        ),
    ]
