# Generated by Django 4.2.2 on 2024-02-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_course_alter_quiz_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='module',
        ),
    ]
