# Generated by Django 4.2.2 on 2024-02-10 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_module_quiz'),
        ('quiz', '0004_remove_quiz_course_remove_quiz_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_course', to='main.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_module', to='main.module'),
            preserve_default=False,
        ),
    ]
