# Generated by Django 4.2.2 on 2024-02-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_choice_question_quizresult_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='duration',
            field=models.PositiveIntegerField(default=600),
        ),
    ]
