# Generated by Django 4.2.2 on 2024-02-10 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quiz_course_remove_quiz_module'),
        ('main', '0005_remove_test_associated_module_delete_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizes_modules', to='quiz.quiz'),
            preserve_default=False,
        ),
    ]
