# Generated by Django 4.2.2 on 2024-02-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_module_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='quiz',
        ),
    ]
