# Generated by Django 4.2.2 on 2024-02-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_course_category_alter_course_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(default='uncategorized', max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
