# Generated by Django 4.2.2 on 2024-02-12 17:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_level_alter_course_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
