# Generated by Django 4.2.2 on 2024-02-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_course_content_alter_module_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='parent_module',
        ),
        migrations.DeleteModel(
            name='Main_Module',
        ),
    ]
