# Generated by Django 4.2.2 on 2024-07-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0018_alter_contact_us_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='message',
            field=models.TextField(),
        ),
    ]
